<a href="https://colab.research.google.com/github/SlowikJakub/AI-Homework/blob/Homework0/Homework0Problem4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import torch
model = torch.hub.load('pytorch/vision:v0.6.0', 'mobilenet_v2', pretrained=True)
model.eval()

Using cache found in /root/.cache/torch/hub/pytorch_vision_v0.6.0


MobileNetV2(
  (features): Sequential(
    (0): ConvBNReLU(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
    (1): InvertedResidual(
      (conv): Sequential(
        (0): ConvBNReLU(
          (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (2): InvertedResidual(
      (conv): Sequential(
        (0): ConvBNReLU(
          (0): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=Tr

In [19]:
from PIL import Image
input_image1 = Image.open("/content/drive/MyDrive/AI images/447px-Gutenberg_Bible,_Lenox_Copy,_New_York_Public_Library,_2009._Pic_01.jpg")
input_image2 = Image.open("/content/drive/MyDrive/AI images/_111434467_gettyimages-1143489763.jpg")
input_image3 = Image.open("/content/drive/MyDrive/AI images/images.jpg")
input_image4 = Image.open("/content/drive/MyDrive/AI images/index.jpg")
input_image5 = Image.open("/content/drive/MyDrive/AI images/istockphoto-466175630-612x612.jpg")

In [20]:

from torchvision import transforms

preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

input_tensor1 = preprocess(input_image1)
input_batch1 = input_tensor1.unsqueeze(0)
input_tensor2 = preprocess(input_image2)
input_batch2 = input_tensor2.unsqueeze(0)
input_tensor3 = preprocess(input_image3)
input_batch3 = input_tensor3.unsqueeze(0)
input_tensor4 = preprocess(input_image4)
input_batch4 = input_tensor4.unsqueeze(0)
input_tensor5 = preprocess(input_image5)
input_batch5 = input_tensor5.unsqueeze(0)


In [21]:

# move the input and model to GPU for speed if available
if torch.cuda.is_available():
    input_batch1 = input_batch1.to('cuda')
    model.to('cuda')
    input_batch2 = input_batch2.to('cuda')
    model.to('cuda')
    input_batch3 = input_batch3.to('cuda')
    model.to('cuda')
    input_batch4 = input_batch4.to('cuda')
    model.to('cuda')
    input_batch5 = input_batch5.to('cuda')
    model.to('cuda')

with torch.no_grad():
    output1 = model(input_batch1)
    output2 = model(input_batch2)
    output3 = model(input_batch3)
    output4 = model(input_batch4)
    output5 = model(input_batch5)
# Tensor of shape 1000, with confidence scores over Imagenet's 1000 classes


In [22]:
print(output1[0])
probabilities1 = torch.nn.functional.softmax(output1[0], dim=0)
print(probabilities1)

tensor([-2.7388,  0.7439, -3.2720, -4.2379, -4.2815, -4.0611, -3.2959,  2.0916,
         1.0989, -2.0933,  0.0231,  0.1576, -2.2034, -1.0907, -4.2084, -2.9224,
        -1.5523, -3.8363, -1.9910,  0.0568, -0.4407, -3.3810, -6.2157, -0.6689,
        -4.0799, -2.0158, -3.8920, -4.1384, -3.9552, -3.3960, -2.8273, -3.5024,
        -4.2624, -2.2741, -2.9697,  0.2601, -1.2520, -0.0261, -2.6988, -0.3241,
         0.9044, -1.3905, -1.6635,  0.1086, -2.6997,  2.3360, -0.3280, -0.7607,
         0.0598, -5.6504, -4.6367, -1.0907,  0.1220, -4.3760, -0.9842, -1.3137,
         0.0100, -5.1796, -1.6548, -2.4996,  0.8286,  4.1021,  1.2171, -0.3380,
        -2.4198, -3.0867, -3.1585, -2.9088, -5.0578,  2.6935, -1.2520, -0.3151,
        -0.7001, -0.6909, -0.5377, -2.0256,  0.7702,  2.2201, -1.0913, -1.5276,
        -1.7302, -2.2528, -0.6208, -2.3236, -2.2186, -0.2744,  0.3797, -0.3833,
        -2.8809, -4.2258, -2.8370, -0.3614, -3.5162, -2.6236, -2.3790, -3.7037,
        -2.6157, -0.1201, -3.3575, -2.65

In [23]:
print(output2[0])
probabilities2 = torch.nn.functional.softmax(output2[0], dim=0)
print(probabilities2)

tensor([-1.1313e+00,  8.4121e-01, -1.8789e+00, -4.4013e-01, -1.0311e+00,
        -3.5659e+00, -3.1547e+00, -1.7600e+00, -6.6314e-01, -3.1581e+00,
         2.4055e+00, -9.2689e-01,  2.1821e+00,  9.0428e-01, -2.1806e+00,
         2.9636e-01, -2.4535e+00, -3.5331e+00, -2.8481e+00, -2.9187e+00,
        -5.0017e-01, -7.3652e-01, -3.2058e+00, -1.8686e+00, -1.1794e+00,
        -3.5367e+00, -2.7848e+00, -1.7077e+00, -2.2207e+00,  1.2557e-01,
        -2.8558e+00, -3.9529e+00, -3.3281e+00, -4.1862e+00, -6.7564e-01,
        -2.0355e+00,  9.8332e-02, -1.4604e+00,  4.8336e-01,  3.3039e-01,
        -1.3833e+00,  7.8221e-01, -3.0588e+00, -9.1987e-01, -2.0855e+00,
        -3.8154e+00, -1.0459e+00, -1.4822e+00, -2.7397e+00, -4.1437e+00,
        -3.1216e+00, -1.1909e+00, -1.3957e+00, -2.4014e+00,  1.8814e-01,
        -2.7561e+00, -4.2614e+00, -1.1462e+00, -2.4121e+00, -2.0547e-01,
        -9.8912e-01, -1.7145e+00, -1.5062e+00, -2.2257e-01, -9.9426e-01,
        -4.0142e+00, -4.7498e-01,  8.7726e-01, -1.2

In [24]:
print(output3[0])
probabilities3 = torch.nn.functional.softmax(output3[0], dim=0)
print(probabilities3)

tensor([ 4.0260e-01, -2.7546e-01, -5.8638e-01, -4.4638e+00, -1.4944e+00,
         2.7228e+00, -2.9453e+00,  5.3514e+00,  9.5447e+00,  2.6862e+00,
         3.7721e+00,  5.2192e+00,  2.0747e+00,  1.5525e+00, -1.9815e+00,
        -1.0437e+00,  4.3053e-01, -2.9146e+00, -3.2871e+00,  2.1844e+00,
        -1.4808e+00,  3.3964e+00, -7.5931e-01,  2.5990e+00, -1.9424e+00,
        -1.0750e+00,  3.3279e+00,  3.2367e+00, -1.5558e-01,  3.1892e+00,
        -6.0811e-01, -3.0803e-01,  4.8058e+00,  8.1247e-01,  2.1062e+00,
         2.8003e+00,  4.1728e+00,  5.7501e-01,  5.2391e+00,  4.6571e+00,
        -1.1665e+00,  4.4250e+00,  4.7388e+00,  5.2764e+00,  5.3207e-01,
         2.2180e+00,  9.4445e-01,  5.4527e+00,  9.0350e-01, -1.9426e+00,
        -4.8680e+00, -7.7519e-01, -1.0414e-01, -1.9608e+00,  8.7003e-01,
        -3.1151e+00, -1.9558e+00,  3.2859e+00, -1.7532e+00, -1.4965e+00,
         2.3467e+00, -2.8539e+00, -1.3627e+00,  4.8862e+00,  4.2098e-01,
        -1.8109e+00,  4.4639e+00,  3.5857e-01,  3.3

In [25]:
print(output4[0])
probabilities4 = torch.nn.functional.softmax(output4[0], dim=0)
print(probabilities4)

tensor([ 1.8154e+00, -3.2882e+00, -2.2136e+00, -1.0084e+00, -1.4743e+00,
        -3.2542e-01, -4.2167e+00,  6.5707e-02,  2.4764e+00, -8.7521e-01,
         1.2170e+01,  1.4769e+01,  4.6366e+00,  6.1909e+00,  9.7539e+00,
         3.7224e+00,  1.2526e+01,  1.8822e+01,  9.8537e+00,  1.6203e+01,
         8.9671e+00,  8.7178e+00, -1.1171e+00,  3.9886e-01,  8.0940e-01,
        -1.5909e+00, -3.6072e-01, -3.0353e+00,  3.4804e-01, -1.8095e+00,
        -2.8462e+00, -1.2666e+00, -9.6394e-01, -4.0920e+00, -1.6878e+00,
        -2.2108e+00,  8.0800e-02, -4.7771e+00,  4.7808e-01, -3.6401e+00,
         1.6497e+00,  1.0501e+00,  1.0505e+00,  5.4285e-01,  2.2080e-01,
        -3.7670e+00, -2.0993e-01,  1.4336e-01, -4.1968e+00, -2.2112e+00,
        -1.4410e+00, -2.3395e+00, -3.1275e-01,  1.5341e+00, -8.4591e-01,
         1.2379e-01,  1.8501e-01, -1.6321e+00,  1.3594e+00,  5.6756e+00,
         1.2201e+00, -1.0645e-01,  3.1389e+00,  1.2450e+00,  2.0775e+00,
         2.7188e+00,  1.2530e+00, -2.4175e+00,  1.5

In [26]:
print(output5[0])
probabilities5 = torch.nn.functional.softmax(output5[0], dim=0)
print(probabilities5)

tensor([-6.1431e+00, -5.4561e-01, -3.0001e+00, -3.7687e+00, -3.3522e+00,
         2.2081e+00, -1.5921e+00,  3.1879e+00, -2.7129e-01,  5.8754e-01,
        -1.6642e+00, -2.0043e+00, -1.5932e+00, -3.6667e+00, -2.7601e+00,
        -1.0666e+00, -1.8123e+00, -2.3545e+00, -1.5256e+00, -2.1281e+00,
        -2.1059e+00, -3.3338e+00, -8.3947e+00, -4.2189e+00, -3.2640e+00,
        -3.7981e+00, -1.0379e+00, -5.8153e-01, -4.5246e+00, -1.2490e+00,
        -2.9718e+00,  2.5798e-01, -1.0504e+00, -3.7859e+00, -3.1737e+00,
        -4.2700e+00, -5.8686e-01, -4.2800e+00, -1.0588e+00,  2.6048e-01,
         3.1338e+00, -2.4382e+00, -2.8157e-01, -1.3016e+00,  3.7143e-01,
        -3.7989e+00,  3.3928e+00,  1.9384e+00, -6.2211e+00, -3.9278e+00,
        -4.2453e+00, -1.7662e+00,  1.8156e-01, -1.0406e+00, -6.8761e-01,
         1.7031e+00, -3.1728e+00, -1.9021e+00, -2.6687e+00,  2.2012e+00,
        -1.2536e+00, -2.5081e+00, -2.3985e+00, -3.4911e+00, -2.2757e-01,
        -4.1311e+00,  2.2619e+00, -1.7764e+00, -4.6

In [27]:
!wget https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt

--2021-02-10 02:35:37--  https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10472 (10K) [text/plain]
Saving to: ‘imagenet_classes.txt.1’

imagenet_classes.tx 100%[===================>]  10.23K  --.-KB/s    in 0s      

2021-02-10 02:35:38 (115 MB/s) - ‘imagenet_classes.txt.1’ saved [10472/10472]



In [28]:
with open("imagenet_classes.txt", "r") as f:
    categories = [s.strip() for s in f.readlines()]
# Show top categories per image
top5_prob, top5_catid = torch.topk(probabilities1, 5)
for i in range(top5_prob.size(0)):
    print(categories[top5_catid[i]], top5_prob[i].item())

grand piano 0.32306843996047974
printer 0.03736276924610138
upright 0.03627372533082962
table lamp 0.02488807961344719
photocopier 0.020992249250411987


In [29]:
with open("imagenet_classes.txt", "r") as f:
    categories = [s.strip() for s in f.readlines()]
# Show top categories per image
top5_prob, top5_catid = torch.topk(probabilities2, 5)
for i in range(top5_prob.size(0)):
    print(categories[top5_catid[i]], top5_prob[i].item())

tabby 0.6329962015151978
tiger cat 0.17828938364982605
Egyptian cat 0.14886097609996796
mouse 0.0063998824916779995
plastic bag 0.004279187880456448


In [30]:
with open("imagenet_classes.txt", "r") as f:
    categories = [s.strip() for s in f.readlines()]
# Show top categories per image
top5_prob, top5_catid = torch.topk(probabilities3, 5)
for i in range(top5_prob.size(0)):
    print(categories[top5_catid[i]], top5_prob[i].item())

porcupine 0.9758628606796265
weasel 0.006231587380170822
fox squirrel 0.0046924506314098835
meerkat 0.003881121752783656
black-footed ferret 0.003043580334633589


In [31]:
with open("imagenet_classes.txt", "r") as f:
    categories = [s.strip() for s in f.readlines()]
# Show top categories per image
top5_prob, top5_catid = torch.topk(probabilities4, 5)
for i in range(top5_prob.size(0)):
    print(categories[top5_catid[i]], top5_prob[i].item())

jay 0.9131197929382324
chickadee 0.06657996028661728
goldfinch 0.01587606593966484
bulbul 0.0016836095601320267
brambling 0.0011795575264841318


In [32]:
with open("imagenet_classes.txt", "r") as f:
    categories = [s.strip() for s in f.readlines()]
# Show top categories per image
top5_prob, top5_catid = torch.topk(probabilities5, 5)
for i in range(top5_prob.size(0)):
    print(categories[top5_catid[i]], top5_prob[i].item())

hip 0.6333395838737488
strawberry 0.20440874993801117
bell pepper 0.13767701387405396
vase 0.004631401970982552
pomegranate 0.004462257958948612
